MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/../data/tct/TorchModelZoo/pretrained_models/hrnet/hrnetv2_w40_imagenet_pretrained.pth"
  BACKBONE:
    CONV_BODY: "HRNET-W40-FPN"
    FREEZE_CONV_BODY_AT: -1


  FPN:
    USE_GN: True
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (16, 32, 64, 128, 256)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    MIN_SIZE: 0
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    USE_GN: True
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "PAN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
INPUT:
  BRIGHTNESS: 0.1
  SATURATION: 0.2
  CONTRAST: 0.2
  HUE: 0.0
DATASETS:
  TRAIN: ("tct_train", )
  TEST: ("tct_test", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (280000, 300000)
  MAX_ITER: 320000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 10000
  DECAY_METHOD: "step"
TEST:
  BBOX_AUG:
    ENABLED: False
    H_FLIP: False
OUTPUT_DIR: "/home/../data/tct/Models/TorchModels/hrnet_40/no_dcn_step_adapool"