MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    FREEZE_CONV_BODY_AT: -1

  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    TRANS_FUNC: "BottleneckWithGN"
    STEM_FUNC: "StemWithGN"

  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (16, 32, 64, 128, 256)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    MIN_SIZE: 10

INPUT:
  BRIGHTNESS: 0.1
  SATURATION: 0.2
  CONTRAST: 0.2
  HUE: 0.0

DATASETS:
  TRAIN: ("tct_train", )
  TEST: ("tct_test", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, 90000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 10000
TEST:
  BBOX_AUG:
    ENABLED: False
    H_FLIP: False
OUTPUT_DIR: "/home/../data/tct/Models/TorchModels/res50_fpn/rpn_only_with_neg"